# Generated by Django 4.2.7 on 2023-11-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainTables",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("carat_range", models.TextField(max_length=25)),
                ("tabel_date", models.DateTimeField(auto_now_add=True)),
                ("shape", models.TextField(max_length=25)),
                ("text_description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="DataManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("D_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("D_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("D_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("D_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("D_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("D_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("D_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("E_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("F_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("G_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("H_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("I_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_IF", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_VV1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_VV2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_VS1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_VS2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_SI1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("J_SI2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("increased", models.TextField(max_length=500)),
                ("dropped", models.TextField(max_length=500)),
                (
                    "current_percentage_change",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "last_percentage_change",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "second_last_percentage_change",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "parent_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.maintables",
                    ),
                ),
            ],
        ),
    ]
