# Generated by Django 4.2.7 on 2023-11-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_datamanager_modified_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamanager",
            name="current_percentage_change",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="datamanager",
            name="last_percentage_change",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="datamanager",
            name="second_last_percentage_change",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
