# Generated by Django 4.2.7 on 2024-01-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_datamanager_d_if_alter_datamanager_d_vs1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uimanager",
            name="UI_position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
