# Generated by Django 4.2.7 on 2023-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_datamanager_postion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamanager",
            name="postion",
            field=models.IntegerField(unique=True),
        ),
    ]
